# Generated by Django 3.0.4 on 2020-03-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Saw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Seen')),
                ('where', models.CharField(choices=[('T', 'Yes, there'), ('NT', 'No, not there'), ('WT', 'Was there earlier')], default='T', max_length=2)),
                ('homie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Homie')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='homie',
            name='locations',
            field=models.ManyToManyField(to='main_app.Location'),
        ),
    ]
