# Generated by Django 3.0.4 on 2020-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200320_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saw',
            name='where',
            field=models.CharField(choices=[('T', 'Yes, there'), ('NT', 'No, not there'), ('WT', 'Was there earlier')], default='T', max_length=2, verbose_name='Still there?'),
        ),
    ]
